### PR TITLE
Check for nil before dereferencing the schema field of a Parameter

### PR DESCRIPTION
**Pull request by davidvc**
I caught this issue while testing swagger-diff with some of my endpoints.  Checking for nil seems to solve the problem.

### CODE REVIEW

**Comment by jeffreyc** [comment]
Thank you for your PR! I think this is a subset of the problem you reported in #6, which means it should be fixed by #8.

Thanks to your report in #6, we found a bug parsing "header" and "formData" parameters. `schema` is required for "body" parameters, so the conditional shouldn't be needed. But prior to #8, "header" and "formData" parameters, which don't have a `schema`, were hitting this line, which would not have worked.

I'll update this PR when 1.0.3 is released (probably this afternoon) so you can grab the latest version and verify that it addresses this issue for you.

**Comment by davidvc** [comment]
Great, thanks!  I have hit a couple more bugs which I'll try to track
down.  Would it help to send you the JSON causing the errors?

**Comment by jeffreyc** [comment]
If your bugs are related to header or formData parameters, they may be fixed in 1.0.3, but if not, we welcome issues (and pull requests), and would definitely appreciate sample Swagger that triggers the bug. Thanks!

**Comment by jeffreyc** [comment]
I just released 1.0.3. Hopefully that will address the bugs you've encountered, but if not, please file issues or create pull requests. Thanks!

**Pull request closed without merging**
